/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'himaja' at '2/7/16 6:25 PM' with Gradle 2.6
 *
 * @author himaja, @date 2/7/16 6:25 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
